server:
  port: 8080
spring:
  application:
    name: consumer-user
  eureka:
    instance:
      prefer-ip-address: true #注册时使用ip地址
    client:
      #      register-with-eureka: false # 不把自己注册到eureka上面
      #      fetch-registry: false # 不从服务器上面来获取注册信息
      service-url:
        defaultZone: http://47.106.147.90:8761/eureka/