server:
  port: 9001
spring:
  zipkin:
    base-url: http://localhost:9600/ #指定了Zipkin服务器的地址
    sleuth:
      sampler:
        percentage: 1.0 # Spring Cloud Sleuth有一个Sampler策略，可以通过这个实现类来控制采样算法
  application:
    name: provider-ticket
  eureka:
    instance:
      prefer-ip-address: true #注册时使用ip地址
    client:
      #      register-with-eureka: false # 不把自己注册到eureka上面
      #      fetch-registry: false # 不从服务器上面来获取注册信息
      service-url:
        defaultZone: http://localhost:8761/eureka/